Age 44 added
cloudba-ru/openpoll pull request #56
Opened 2019-04-16 16:50 UTC by Firsov974

Добавлен еще один вариант возраста

2019-04-16 18:15 UTC, cloudba-ru requested changes
Необходимо разрешить конфликт

2019-04-17 13:40 UTC, Berezkin-dv approved these changes

2019-04-17 13:40 UTC, Berezkin-dv approved these changes

2019-04-17 13:41 UTC, Berezkin-dv approved these changes

2019-04-17 13:45 UTC, closed without merging

2019-04-17 13:45 UTC, Berezkin-dv commented
Просьба провести повторный коммит. Разрешить конфликт не удалось.